# Étape 1 : Build du JAR avec Maven
FROM maven:3.9.6-eclipse-temurin-17 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Étape 2 : Image d'exécution légère
FROM openjdk:17-jre-slim
WORKDIR /app
COPY --from=build /app/target/batch-processing-*.jar app.jar
USER nobody
EXPOSE 8080
ENV SPRING_PROFILES_ACTIVE=railway
CMD ["java", "-jar", "app.jar"] 